[build]
publish = "."
functions = "netlify/functions"

[functions]
external_node_modules = ["pg", "bcryptjs"]
node_bundler = "esbuild"

[[redirects]]
from = "/.netli/functions
to = "/'netlify/functions/:sssplat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200